kind: pipeline
name: default

steps:
  - name: deploy
    image: gperiard/docker-compose:latest
    commands:
      - docker-compose build
      - docker-compose restart
    environment:
      DOCKER_HOST: /var/run/docker.sock
    volumes:
    - name: docker
      host:
        path: /var/run/docker.sock
