kind: pipeline
name: default

steps:
  - name: deploy
    image: gperiard/docker-compose:latest
    commands:
      - docker-compose build
      - docker-compose restart
    environment:
      DOCKER_HOST: http+unix://var/run/docker.sock
    volume:
      - /var/run/docker.sock:/var/run/docker.sock
