version: '3'

services:
  nginx:
    build:
      dockerfile: docker/Dockerfile.nginx
      context: .
    ports:
      - 8090:80
    networks:
      - gti525-venue
    depends_on:
      - uwsgi
  db:
    image: mariadb
    environment:
            MYSQL_USER: venue
            MYSQL_PASSWORD: venue
            MYSQL_DATABASE: venue
            MYSQL_ROOT_PASSWORD: venue
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - gti525-venue
  uwsgi:
    build:
      dockerfile: docker/Dockerfile.uwsgi
      context: .
    depends_on:
      - db
    environment:
      DB_TYPE: mysql
    command: |
      bash -c "bash -s <<EOF
      ./utils/wait-for-it.sh db:3306 && \
      python manage.py migrate && \
      uwsgi --socket 0.0.0.0:8000 --wsgi-file venue/wsgi.py
      EOF"
    networks:
      - gti525-venue

volumes:
  db_data:

networks:
  gti525-venue:
