# Generated by Django 2.1.5 on 2019-02-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0006_auto_20190227_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billet',
            name='sold',
        ),
    ]
