# Generated by Django 2.1.5 on 2019-01-31 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test_App', '0002_myuuidmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUUIDModel',
            new_name='Ticket',
        ),
    ]
