# Generated by Django 2.1.5 on 2019-01-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_App', '0003_auto_20190130_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='short_name',
            field=models.CharField(default='Test', max_length=10),
        ),
    ]
