# Generated by Django 2.1.5 on 2019-02-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_App', '0004_ticket_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='name2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
