# Generated by Django 2.1.7 on 2019-03-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_auto_20190308_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='ticket_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
