# Generated by Django 2.1.7 on 2019-03-19 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_show_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, 'CREATED'), (1, 'ON SALE'), (2, 'SALE ENDED')], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='seller',
            name='url',
        ),
        migrations.AddField(
            model_name='seller',
            name='base_url',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='client_class',
            field=models.CharField(choices=[('Vente1Client', 'Vente1Client'), ('Vente2Client', 'Vente2Client')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='token',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='image_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='showpublication',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.Seller'),
        ),
        migrations.AddField(
            model_name='showpublication',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.Show'),
        ),
    ]
