# Generated by Django 2.1.7 on 2019-03-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_auto_20190319_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='showpublication',
            name='tickets',
            field=models.ManyToManyField(to='venue.Ticket'),
        ),
    ]
