FROM python:3

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y curl software-properties-common
RUN curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
RUN apt-get install nodejs

RUN mkdir /app
WORKDIR /app

ADD venue/ ./

RUN pip install -r requirements.txt
