version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_TYPE: mysql
    command: |
      bash -c "bash -s <<EOF
      python manage.py migrate && \
      python manage.py runserver 0.0.0.0:8000
      EOF"
