# Generated by Django 2.1.5 on 2019-02-27 01:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_billet'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='idBillet',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
