# Generated by Django 2.1.5 on 2019-02-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_billet_idbillet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billet',
            name='idBillet',
            field=models.UUIDField(),
        ),
    ]
