# Generated by Django 2.1.5 on 2019-02-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0007_remove_billet_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='idMobile',
            field=models.CharField(default='mobile1', max_length=150),
            preserve_default=False,
        ),
    ]
