# Generated by Django 2.1.5 on 2019-02-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0008_billet_idmobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
