# Generated by Django 2.1.7 on 2019-03-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0010_remove_billet_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
