# Generated by Django 2.1.7 on 2019-03-07 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0011_billet_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billet',
            name='date',
        ),
    ]
