# Generated by Django 2.1.7 on 2019-03-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0013_billet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billet',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
