# Generated by Django 2.1.7 on 2019-03-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ticket_uuid', models.UUIDField(editable=False)),
                ('status', models.CharField(choices=[('OK', 'Scanné, OK'), ('FAIL', 'Déjà scanné! FAIL')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('show', models.UUIDField(editable=False)),
                ('scanned', models.BooleanField(default=False)),
            ],
        ),
    ]
