# Generated by Django 2.1.7 on 2019-03-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_validator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='show',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('uuid', 'show')},
        ),
    ]
