# Generated by Django 2.1 on 2019-03-29 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_validator', '0003_scanlog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanlog',
            old_name='user',
            new_name='mobile_user',
        ),
    ]
