version: '3'

services:
  db:
    image: mariadb
    environment:
            MYSQL_USER: venue
            MYSQL_PASSWORD: venue
            MYSQL_DATABASE: venue
            MYSQL_ROOT_PASSWORD: venue
    volumes:
      - db_data:/var/lib/mysql
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: |
      bash -c "bash -s <<EOF
      python manage.py migrate && \
      python manage.py runserver 0.0.0.0:8000
      EOF"

volumes:
  db_data:
