version: '3'

services:
  db:
    image: mariadb
    environment:
            MYSQL_USER: venue
            MYSQL_PASSWORD: venue
            MYSQL_DATABASE: venue
            MYSQL_ROOT_PASSWORD: venue
    volumes:
      - db_data:/var/lib/mysql
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_TYPE: mysql
    command: |
      bash -c "bash -s <<EOF
      ./utils/wait-for-it.sh db:3306 && \
      python manage.py makemigrations && \
      python manage.py migrate && \
      python manage.py runserver 0.0.0.0:8080
      EOF"

volumes:
  db_data:
